image:
  file: .gitpod.Dockerfile
tasks:
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - init: |
      chmod +x ./start-mongodb.sh
      ./start-mongodb.sh latest "" 27019 workplan Mike teamway
      yarn

# ports:
#   # response of root request will be appeared in the browser
#   - port: 3000
#     name: root response
#     onOpen: open-browser
#     visibility: public
